### ISSUE TITLE
CI: generate artifacts

### ISSUE THREAD

**Issue by batazor** [micro-company/react-app#14]
- Stats use dependencies

```
.job_template_build: &job_build
  type: build
  retry: 2
  artifacts:
    paths:
    - dist/stats.html
    expire_in: 1 week
  only:
  - tags
  when: on_success

```
